const mongoose=require('mongoose')
const Schema=mongoose.Schema           //To enable Creation of Models and Schemas
const movieSchema=new Schema(        //Creating a Schema
    {
        plot:{
            type:String,
            required:true              //If the Type Satisfies then it will proceed
        },
        genres:{
            type:Array,
            required:true
        },
        runtime:{
            type:Number,
            required:true
        },
        cast:{
            type:Array,
            required:true
        },
        poster:{
            type:String,
            required:true
        },
        title:{
            type:String,
            required:true
        },
        fullplot:{
            type:String,
            required:true
        },
        languages:{
            type:Array,
            default:["English"]
        },
        released:{
            type:Date,
            required:true
        },
        directors:{
            type:Array,
            required:true
        },
        writers:{
            type:Array,
            required:true
        },
        rated:{
            type:String,
            default:['NOT RATED']
        },
        awards:{
            type:Object,
            required:false
        },
        lastupdated:{
            type:String,
            required:true
        },
        year:{
            type:Number,
            required:true
        },
        imdb:{
            type:Object,
            required:false
        },
        countries:{
            type:Array,
            required:true
        },
        type:{
            type:String,
            default:'movie'
        },
        tomatoes:{
            type:Object,
            required:false
        },
        comments:{
            type:Number,
            default:0
        }},
        { versionKey: false }                       //Removes the __v key while we POST any Movie
        )
module.exports=mongoose.model('Movie', movieSchema)